In [1]:
import pandas as pd
import math
from typing import List
from datetime import datetime
from sqlalchemy import MetaData, Table, create_engine, text
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import Integer

In [2]:
import sys
import os

In [3]:
engine = create_engine('sqlite:///pare.db')

In [4]:
sys.path.append(os.path.join(os.path.dirname('__file__'), 'models'))
sys.path.append(os.path.join(os.path.dirname('__file__'), 'scripts'))
sys.path.append(os.path.join(os.path.dirname('__file__'), 'config'))

In [5]:
from config.params import DEBUG

In [6]:
file_root = './inputs/'

In [7]:
file_path = file_root + 'indicators.xlsx'

In [8]:
# Load the Excel file
excel_data = pd.ExcelFile(file_path)

# Dictionary to store DataFrames for each sheet
dataframes = {}

# Loop through each sheet name
for sheet_name in excel_data.sheet_names:
    # Read the sheet into a DataFrame
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    # Store the DataFrame in the dictionary
    dataframes[sheet_name] = df
    print(f"DataFrame for sheet '{sheet_name}' created successfully!")

# Optionally display the DataFrames
for sheet_name, df in dataframes.items():
    print(f"\nDataFrame for sheet: {sheet_name}")
    print(df)

DataFrame for sheet 'Participants' created successfully!
DataFrame for sheet 'Engagements' created successfully!
DataFrame for sheet 'TechnicalSupports' created successfully!
DataFrame for sheet 'Sales' created successfully!
DataFrame for sheet 'AccessToFinance' created successfully!

DataFrame for sheet: Participants
   Quarter_end_date  Target_female  Target_male  Target_less_30  \
0        2023-03-31     226.200000        527.8      150.800000
1        2023-06-30     240.000000        560.0      160.000000
2        2023-09-30     240.000000        560.0      160.000000
3        2023-12-31     360.000000        840.0      240.000000
4        2024-03-31     497.571429       1161.0      331.714286
5        2024-06-30     497.571429       1161.0      331.714286
6        2024-09-30     497.571429       1161.0      331.714286
7        2024-12-31     495.000000       1155.0      330.000000
8        2025-03-31     360.000000        840.0      240.000000
9        2025-06-30     360.000000        840.0      240.000000
10       2025-09-30     360.000000        840.0      240.000000
11       2025-12-31     360.000000        840.0      240.000000
12       2026-03-31     642.000000       1498.0      428.000000
13       2026-06-30     480.000000       1120.0      320.000000
14       2026-09-30     336.000000        784.0      224.000000
15       2026-12-31     624.000000       1456.0      416.000000
16       2027-03-31     624.000000       1456.0      416.000000
17       2027-06-30     450.000000       1050.0      300.000000
18       2027-09-30     660.000000       1540.0      440.000000
19       2027-12-31     732.000000       1708.0      488.000000

    Target_30_and_plus   Target_sex   Target_age  Total_target   Value_male  \
0           603.200000   754.000000   754.000000    754.000000     0.000000
1           640.000000   800.000000   800.000000    800.000000   840.000000
2           640.000000   800.000000   800.000000    800.000000  1218.000000
3           960.000000  1200.000000  1200.000000   1200.000000     0.000000
4          1326.857143  1658.571429  1658.571429   1658.571429   910.000000
5          1326.857143  1658.571429  1658.571429   1658.571429     0.000000
6          1326.857143  1658.571429  1658.571429   1658.571429  1218.000000
7          1320.000000  1650.000000  1650.000000   1650.000000   408.800000
8           960.000000  1200.000000  1200.000000   1200.000000   166.314186
9           960.000000  1200.000000  1200.000000   1200.000000   777.230316
10          960.000000  1200.000000  1200.000000   1200.000000   840.234193
11          960.000000  1200.000000  1200.000000   1200.000000  1204.087431
12         1712.000000  2140.000000  2140.000000   2140.000000  1637.042752
13         1280.000000  1600.000000  1600.000000   1600.000000  2466.914529
14          896.000000  1120.000000  1120.000000   1120.000000  3379.600000
15         1664.000000  2080.000000  2080.000000   2080.000000  1310.571808
16         1664.000000  2080.000000  2080.000000   2080.000000  1248.800000
17         1200.000000  1500.000000  1500.000000   1500.000000   920.284597
18         1760.000000  2200.000000  2200.000000   2200.000000  1613.699872
19         1952.000000  2440.000000  2440.000000   2440.000000   896.523412

    Value_female  Value_less_30  Value_30_and_plus    value_sex    Value_age  \
0       0.000000       0.000000           0.000000     0.000000     0.000000
1     360.000000     240.000000         960.000000  1200.000000  1200.000000
2     522.000000     348.000000        1392.000000  1740.000000  1740.000000
3       0.000000       0.000000           0.000000     0.000000     0.000000
4     390.000000     260.000000        1040.000000  1300.000000  1300.000000
5       0.000000       0.000000           0.000000     0.000000     0.000000
6     522.000000     348.000000        1392.000000  1740.000000  1740.000000
7     175.200000     116.800000         467.200000   584.000000   584.000000
8      71.277508      47.518339         190.073356   237.591694   237.591694
9     333.098707     222.065805         888.263219  1110.329023  1110.329023
10    360.100369     240.066912         960.267649  1200.334562  1200.334562
11    516.037470     344.024980        1376.099921  1720.124901  1720.124901
12    701.589751     467.726501        1870.906002  2338.632503  2338.632503
13   1057.249084     704.832723        2819.330890  3524.163613  3524.163613
14   1448.400000     965.600000        3862.400000  4828.000000  4828.000000
15    561.673632     374.449088        1497.796352  1872.245440  1872.245440
16    535.200000     356.800000        1427.200000  1784.000000  1784.000000
17    394.407684     262.938456        1051.753825  1314.692281  1314.692281
18    691.585660     461.057106        1844.228426  2305.285532  2305.285532
19    384.224319     256.149546        1024.598185  1280.747731  1280.747731

    Total_value
0      0.000000
1   1200.000000
2   1740.000000
3      0.000000
4   1300.000000
5      0.000000
6   1740.000000
7    584.000000
8    237.591694
9   1110.329023
10  1200.334562
11  1720.124901
12  2338.632503
13  3524.163613
14  4828.000000
15  1872.245440
16  1784.000000
17  1314.692281
18  2305.285532
19  1280.747731

DataFrame for sheet: Engagements
   Quarter_end_date  Total_target  Total_value
0        2023-03-31             4            3
1        2023-06-30             2            3
2        2023-09-30             3            2
3        2023-12-31             8            6
4        2024-03-31             2            2
5        2024-06-30             3            3
6        2024-09-30             1            1
7        2024-12-31             4            3
8        2025-03-31             9            9
9        2025-06-30             2            1
10       2025-09-30             0            5
11       2025-12-31             0            0
12       2026-03-31             3            4
13       2026-06-30             1            4
14       2026-09-30             2            2
15       2026-12-31             4            7
16       2027-03-31             7            3
17       2027-06-30             0            0
18       2027-09-30             3            2
19       2027-12-31             1            1

DataFrame for sheet: TechnicalSupports
   Quarter_end_date  Total_target  Total_value
0        2023-03-31             3            2
1        2023-06-30             7            7
2        2023-09-30             2            2
3        2023-12-31             9            6
4        2024-03-31             5            2
5        2024-06-30             4            2
6        2024-09-30             5            2
7        2024-12-31             5            4
8        2025-03-31             1            8
9        2025-06-30             5            2
10       2025-09-30             0            5
11       2025-12-31             5            2
12       2026-03-31             5            0
13       2026-06-30             9            8
14       2026-09-30             8           10
15       2026-12-31             5            3
16       2027-03-31             5            7
17       2027-06-30            10           13
18       2027-09-30             5            5
19       2027-12-31             2            6

DataFrame for sheet: Sales
   Quarter_end_date  Total_target   Total_value
0        2023-03-31  2.091366e+06  1.458069e+06
1        2023-06-30  3.012224e+06  2.352129e+06
2        2023-09-30  2.465585e+06  1.276658e+07
3        2023-12-31  2.826200e+06  5.697067e+05
4        2024-03-31  3.428673e+06  8.352000e+05
5        2024-06-30  2.029416e+06  8.893892e+06
6        2024-09-30  1.272172e+07  3.728202e+06
7        2024-12-31  3.070655e+06  1.362972e+06
8        2025-03-31  3.448476e+06  2.886576e+06
9        2025-06-30  5.400937e+06  3.960429e+06
10       2025-09-30  2.525808e+06  2.280337e+06
11       2025-12-31  2.078524e+06  2.127504e+06
12       2026-03-31  2.870046e+06  1.865191e+06
13       2026-06-30  1.089876e+07  9.126668e+06
14       2026-09-30  2.677036e+06  2.073902e+06
15       2026-12-31  1.826421e+06  8.477169e+06
16       2027-03-31  1.522347e+06  1.389750e+06
17       2027-06-30  1.611928e+06  1.519720e+06
18       2027-09-30  1.104320e+06  5.354017e+05
19       2027-12-31  1.689556e+06  1.659539e+06

DataFrame for sheet: AccessToFinance
   Quarter_end_date   Total_target    Total_value
0        2023-03-31   21768.122663    2263.422379
1        2023-06-30   44940.653249   17645.090813
2        2023-09-30   18738.111733   15376.881292
3        2023-12-31   29865.801127   10064.617011
4        2024-03-31   30514.948850    8478.300425
5        2024-06-30   19399.496206   12287.669819
6        2024-09-30   10957.734142  183771.517629
7        2024-12-31   32797.040553   20099.069635
8        2025-03-31   29708.448090   24659.103549
9        2025-06-30   19643.646543    3666.839285
10       2025-09-30   29600.559134    1427.685768
11       2025-12-31   45543.609917   13597.843274
12       2026-03-31   33753.074663    5847.737229
13       2026-06-30   35123.468324   30514.325535
14       2026-09-30   47764.625914   40828.849873
15       2026-12-31   27472.489755   11024.498272
16       2027-03-31  443316.906766  418279.999660
17       2027-06-30   40109.562841   32691.520408
18       2027-09-30   15287.138248  127947.167921
19       2027-12-31   23694.561367   20528.262113