In [1]:
import pandas as pd

In [2]:
from faker import Faker

In [3]:
faker = Faker("fr_FR")

In [4]:
faker.name()

'Juliette Gaillard'

In [5]:
for _ in range(10):
    print(faker.name())

Mathilde Leduc
Sébastien Lesage
Frédéric Maillet-Robin
Thibault Buisson-Moreno
Marcelle Navarro
Marcelle Munoz
Brigitte Blanchet
Thomas Roussel
Joséphine-Monique Bonnin
Nathalie Lévy

In [6]:
class Activity:
    name: str
    act_type: str

In [7]:
#import factory
#
#class ActicityFactory(factory.Factory):
#    class Meta:
#        model = Activity
#
#    name = factory.Faker('sentence', nb_words=100)
#    act_type = factory.Faker('sentence', nb_words=10)

In [8]:
from mimesis import Person
from mimesis.enums import Gender
person = Person('en')

person.full_name(gender=Gender.FEMALE)
#'Antonetta Garrison'
personru = Person('ru')
personru.full_name()
#'Рената Черкасова'

'Ярослава Левитин'

In [10]:
from faker import Faker
import pandas as pd
import random
fake = Faker()

def create_rows_faker(num=1):
    output = [{"name":fake.name(),
                   "address":fake.address(),
                   "name":fake.name(),
                   "email":fake.email(),
                   #"bs":fake.bs(),
                   "city":fake.city(),
                   "state":fake.state(),
                   "date_time":fake.date_time(),
                   #"paragraph":fake.paragraph(),
                   #"Conrad":fake.catch_phrase(),
                   "randomdata":random.randint(1000,2000)} for x in range(num)]
    return output

#%%time
df_faker = pd.DataFrame(create_rows_faker(5000))

In [11]:
df_faker.head()

,name,address,email,city,state,date_time,randomdata
0,Brad Wright,"13546 Matthew Rapids\nPort Tiffanyburgh, KS 24326",beverlyhaynes@example.com,Richardshaven,New York,2006-09-19 20:09:44,1435
1,Kelly Silva,"915 May Roads Suite 146\nSouth Michael, CT 02207",jjarvis@example.com,Mooreside,Alabama,2021-02-14 21:00:17,1847
2,Bradley Williamson,"5717 Carolyn Pines Suite 624\nFosterton, ME 68889",nicole80@example.org,Port Troyland,Kansas,1991-06-06 19:49:38,1595
3,Franklin Johnson,"21685 Carter Road Apt. 131\nReynoldston, AL 94263",sharon37@example.net,Elliotthaven,Illinois,1988-10-02 23:37:11,1080
4,Tiffany Huffman,"560 King Coves Suite 372\nElizabethfort, AK 40668",martinezmolly@example.org,Braunbury,Maryland,2012-12-26 15:37:34,1531

In [12]:
from mimesis import Person
from mimesis import Address
from mimesis.enums import Gender
from mimesis import Datetime
person = Person('en')
import pandas as pd
import random
person = Person()
addess = Address()
datetime = Datetime()
def create_rows_mimesis(num=1):
    output = [{"name":person.full_name(gender=Gender.FEMALE),
                   "address":addess.address(),
                   "name":person.name(),
                   "email":person.email(),
                   #"bs":person.bs(),
                   "city":addess.city(),
                   "state":addess.state(),
                   "date_time":datetime.datetime(),
                   #"paragraph":person.paragraph(),
                   #"Conrad":person.catch_phrase(),
                   "randomdata":random.randint(1000,2000)} for x in range(num)]
    return output

#%%time
df_mimesis = pd.DataFrame(create_rows_mimesis(5000))

In [13]:
df_mimesis.head()

,name,address,email,city,state,date_time,randomdata
0,Theodore,1330 Martin Luther King Jr Cove,monetary1938@outlook.com,Rock Springs,Connecticut,2024-02-24 17:26:56.010652,1768
1,Malika,796 Dutch Windmill Access Glen,feedback2083@example.org,Port St. Lucie,Tennessee,2024-10-15 21:02:00.657843,1236
2,Louetta,162 Peek Crescent,because1927@protonmail.com,Bradenton,Wisconsin,2024-02-22 08:31:56.206424,1307
3,Rodney,1356 Elmhurst Heights,walks2061@yandex.com,Tupelo,Arkansas,2024-09-12 20:18:14.587008,1633
4,Renna,1162 Ignacio Mall,coal1819@live.com,East Cleveland,Texas,2024-11-07 01:46:55.543373,1514

In [14]:
from faker import Faker
import pandas as pd
import random
fake = Faker()
def create_rows(num=1):
    output = [{"name":fake.name(),
               "address":fake.address(),
               "name":fake.name(),
               "email":fake.email(),
               "bs":fake.bs(),
               "address":fake.address(),
               "city":fake.city(),
               "state":fake.state(),
               "date_time":fake.date_time(),
               "paragraph":fake.paragraph(),
               "Conrad":fake.catch_phrase(),
               "randomdata":random.randint(1000,2000)} for x in range(num)]
    return output

df = pd.DataFrame(create_rows(5000))

In [15]:
df.head()

,name,address,email,bs,city,state,date_time,paragraph,Conrad,randomdata
0,Mr. Richard Oconnor,"524 Earl Spurs Apt. 467\nAngelafort, FM 75031",jessica43@example.net,exploit open-source vortals,North James,Alaska,2008-04-23 21:10:28,Part early federal everything wide law. Paper ...,Multi-tiered client-driven knowledge user,1343
1,James Castillo,"961 Yang Corner\nSouth Micheleville, UT 19450",taylormark@example.com,aggregate robust partnerships,Priceview,West Virginia,2010-08-17 07:56:42,History include floor. Example instead middle....,Monitored clear-thinking productivity,1141
2,Lisa Medina,Unit 1595 Box 4599\nDPO AP 64868,llopez@example.net,deploy visionary ROI,Lake Megan,Maine,1996-01-08 18:50:49,Late only hear five individual third. Some sch...,Progressive logistical adapter,1786
3,Katherine Bowman,"12650 Bryan Overpass\nBuchananmouth, TX 18303",kochchad@example.net,enable B2C markets,East Noahside,Michigan,1971-02-20 09:16:52,Special feeling analysis piece. Create realize...,Ergonomic responsive conglomeration,1454
4,Bryan Johns,"6169 Brendan Mount Suite 526\nSouth Shannon, T...",mmosley@example.com,seize killer solutions,Port Jo,Montana,1992-02-07 13:11:02,Window church blood none ready to end. Whose p...,Switchable scalable circuit,1824

In [17]:
for i in range(10):
    stuff = [fake.name()
        , fake.email()
        , fake.bs()
        , fake.address()
        , fake.city()
        , fake.state()
        , fake.date_time()
        , fake.paragraph()
        , fake.catch_phrase()
        , random.randint(1000, 2000)]
    df.loc[i] = [item for item in stuff]
df.head()

,name,address,email,bs,city,state,date_time,paragraph,Conrad,randomdata
0,Melissa Tanner,kennethwillis@example.org,target clicks-and-mortar supply-chains,"PSC 0364, Box 4841\nAPO AP 34770",North Colleenland,Louisiana,2000-06-25 23:50:27,This marriage condition church. Position thoug...,Monitored secondary product,1027
1,Felicia Harrington,tracyclark@example.net,grow interactive convergence,"6063 Anthony Lights\nEast Francismouth, DE 71870",Nathanbury,Illinois,1981-09-18 23:10:13,Religious box bill financial me. He matter aud...,Fundamental exuding database,1385
2,Christina Johnson,yanderson@example.org,target dot-com architectures,"30225 Mcbride Mountains\nWest Kristin, MS 03254",Port Maryfurt,Maryland,1999-01-17 01:47:09,Blue kind modern garden. Teacher loss day.,Operative impactful intranet,1875
3,Connie Cohen,hwiley@example.net,innovate dot-com infrastructures,"PSC 9262, Box 2439\nAPO AE 21560",West John,California,1995-11-20 22:49:55,Whether fall collection situation interest. Ta...,Innovative context-sensitive initiative,1461
4,Dennis Leach,jesusevans@example.com,re-intermediate transparent users,"7397 Patricia Square\nManuelview, FM 90106",Stonemouth,New Hampshire,1993-10-14 22:46:53,Theory family visit loss husband very contain....,Decentralized leadingedge installation,1168

In [23]:
communes_coord = [
             {"name":"Hinche",            "lat": 19.15,         "lng": -72.01667,    "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Cerca Carvajal",    "lat": 19.250,        "lng": -71.950,      "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Cerca La Source",   "lat": 19.1667,       "lng": -71.7833,     "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Fort-Liberté",      "lat": 19.6667,       "lng": -71.8333,     "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Perches",           "lat": 19.52305870,   "lng": -71.92383200, "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Ferrier",           "lat": 19.617,        "lng": -71.783,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},   
             {"name":"Ouanaminthe",       "lat": 19.54807,      "lng": -71.72397,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Mont-Organisé",     "lat": 19.367,        "lng": -71.783,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Trou du Nord",      "lat": 19.63333,      "lng": -72.01667,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Vallières",         "lat": 19.43548,      "lng": -71.92094,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Terrier Rouge",     "lat": 19.600,        "lng": -71.917,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Caracol",           "lat": 19.691,        "lng": -72.016,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Carice",            "lat": 19.350,        "lng": -71.817,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Capotille",         "lat": 19.433,        "lng": -71.717,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Sainte Suzanne",    "lat": 19.58333,      "lng": -72.08333,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Les Cayes",         "lat": 18.19331,      "lng": -73.74601,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Camp-Perrin",       "lat": 18.317,        "lng": -73.867,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Chantal",           "lat": 18.20269,      "lng": -73.88891,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Torbeck",           "lat": 18.1657547,    "lng": -73.8139579,  "Departement": "Sud",              "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Chardonnières",     "lat": 18.26667,      "lng": -74.16667,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Port-à-Piment",     "lat": 18.25000,      "lng": -74.10000,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Roche à Bâteau",    "lat": 18.18333,      "lng": -74.00000,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Port-Salut",        "lat": 18.13333,      "lng": -73.9,        "Departement": "Sud",              "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Arniquet",          "lat": 18.146,        "lng": -73.875,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Saint Jean du Sud", "lat": 18.083,        "lng": -73.850,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Côteaux",           "lat": 18.2072607,    "lng": -74.040294,      "Departement": "Sud",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Acul du Nord",      "lat": 19.6808413-0.041, "lng": -72.317793,   "Departement": "Nord",          "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Plaine du Nord",    "lat": 19.68333,      "lng": -72.26667,    "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Limonade",          "lat": 19.66667,      "lng": -72.11667,    "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Saint-Raphaël",     "lat": 19.43917,      "lng": -72.19972,    "Departement": "Nord",             "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Quartier Morin",    "lat": 19.667+0.03,        "lng": -72.167,      "Departement": "Nord",        "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Ranquitte",         "lat": 19.4129673,    "lng": -72.0808875,  "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Pignon",            "lat": 19.317,        "lng": -72.083,      "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"La Victoire",       "lat": 19.3352998,    "lng": -72.0216309,             "Departement": "Nord",  "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
         ]

In [24]:
locations = [
    {"Departement": "Nord", "Communes": [
                                        'Acul du Nord',
                                        'Plaine du Nord',
                                        'Limonade',
                                        'Saint-Raphaël',
                                        'Quartier Morin',
                                        'Ranquitte',
                                        'Pignon',
                                        'La Victoire',
                                        ] },
    {"Departement": "Sud", "Communes": [
                                        'Les Cayes',
                                        'Camp-Perrin',
                                        'Chantal',
                                        'Torbeck',
                                        'Chardonnières',
                                        'Port-à-Piment',
                                        'Roche à Bâteau',
                                        'Port-Salut',
                                        'Arniquet',
                                        'Saint Jean du Sud',
                                        'Côteaux',] },
    {"Departement": "Nord-Est", "Communes": [
                                        "Fort-Liberté", 
                                        'Perches', 
                                        'Ferrier', 
                                        'Ouanaminthe', 
                                        'Mont-Organisé', 
                                        'Trou du Nord',
                                        'Vallières',
                                        'Terrier Rouge',
                                        'Caracol',
                                        'Carice',
                                        'Capotille',
                                        'Sainte Suzanne'                                         
    ] },
    {"Departement": "Centre", "Communes": [
                                        "Hinche", 
                                        "Cerca Carvajal",
                                        "Cerca La Source"
    ] },
]

In [21]:
locations

[{'Departement': 'Nord',
  'Communes': ['Acul du Nord',
   'Plaine du Nord',
   'Limonade',
   'Saint-Raphaël',
   'Quartier Morin',
   'Ranquitte',
   'Pignon',
   'La Victoire']},
 {'Departement': 'Sud',
  'Communes': ['Les Cayes',
   'Camp-Perrin',
   'Chantal',
   'Torbeck',
   'Chardonnières',
   'Port-à-Piment',
   'Roche à Bâteau',
   'Port-Salut',
   'Arniquet',
   'Saint Jean du Sud',
   'Côteaux']},
 {'Departement': 'Nord-Est',
  'Communes': ['Fort-Liberté',
   'Perches',
   'Ferrier',
   'Ouanaminthe',
   'Mont-Organisé',
   'Trou du Nord',
   'Vallières',
   'Terrier Rouge',
   'Caracol',
   'Carice',
   'Capotille',
   'Sainte Suzanne']},
 {'Departement': 'Centre',
  'Communes': ['Hinche', 'Cerca Carvajal', 'Cerca La Source']}]

In [ ]:
locations_1 = [
    {"Departement": "Nord", "Communes": [
                                        
                                        {'name':'Acul du Nord',   'sections':[], 'localities':[]},
                                        {'name':'Plaine du Nord', 'sections':[], 'localities':[]},
                                        {'name':'Limonade',       'sections':[], 'localities':[]},
                                        {'name':'Saint-Raphaël',  'sections':[], 'localities':[] },
                                        {'name':'Quartier Morin', 'sections':[], 'localities':[] },
                                        {'name':'Ranquitte',      'sections':[], 'localities':[]},
                                        {'name':'Pignon',         'sections':[], 'localities':[] },
                                        {'name':'La Victoire',    'sections':[], 'localities':[]},
                                        ] },
    {"Departement": "Sud", "Communes": [
                                        {'name':'Les Cayes',        'sections':[],'localities':[] },
                                        {'name':'Camp-Perrin',      'sections':[],'localities':[] },
                                        {'name':'Chantal',          'sections':[],'localities':[] },
                                        {'name':'Torbeck',          'sections':[],'localities':[] },
                                        {'name':'Chardonnières',    'sections':[],'localities':[] },
                                        {'name':'Port-à-Piment',    'sections':[],'localities':[] },
                                        {'name':'Roche à Bâteau',   'sections':[],'localities':[] },
                                        {'name':'Port-Salut',       'sections':[],'localities':[] },
                                        {'name':'Arniquet',         'sections':[],'localities':[] },
                                        {'name':'Saint Jean du Sud','sections':[],'localities':[] },
                                        {'name':'Côteaux',          'sections':[],'localities':[] },] },
    {"Departement": "Nord-Est", "Communes": [
                                        {'name':"Fort-Liberté",     'sections':[], 'localities':[]}, 
                                        {'name':'Perches',          'sections':[], 'localities':[]}, 
                                        {'name':'Ferrier',          'sections':[], 'localities':[]}, 
                                        {'name':'Ouanaminthe',      'sections':[], 'localities':[]}, 
                                        {'name':'Mont-Organisé',    'sections':[], 'localities':[]}, 
                                        {'name':'Trou du Nord',     'sections':[], 'localities':[]},
                                        {'name':'Vallières',        'sections':[], 'localities':[]},
                                        {'name':'Terrier Rouge',    'sections':[], 'localities':[]},
                                        {'name':'Caracol',          'sections':[], 'localities':[]},
                                        {'name':'Carice',           'sections':[], 'localities':[]},
                                        {'name':'Capotille',        'sections':[], 'localities':[]},
                                        {'name':'Sainte Suzanne',   'sections':[], 'localities':[]},                                         
    ] },
    {"Departement": "Centre", "Communes": [
                                        {'name':"Hinche",           'sections':[], 'localities':[],}, 
                                        {'name':"Cerca Carvajal",   'sections':[], 'localities':[],},
                                        {'name':"Cerca La Source",  'sections':[], 'localities':[],},
    ] },
]